const imagens = [
    [
        "/janeiro/Hanafuda_January_Hikari.svg.png",
        "/janeiro/Hanafuda_January_Tanzaku.svg.png",
        "/janeiro/Hanafuda_January_Kasu_1.svg.png",
        "/janeiro/Hanafuda_January_Kasu_2.svg.png",
    ],
    [
        "/fevereiro/Hanafuda_February_Tane.svg.png",
        "/fevereiro/Hanafuda_February_Tanzaku.svg.png",
        "/fevereiro/Hanafuda_February_Kasu_1.svg.png",
        "/fevereiro/Hanafuda_February_Kasu_2.svg.png",
    ],
    [
        "/marco/Hanafuda_March_Hikari.svg.png",
        "/marco/Hanafuda_March_Tanzaku.svg.png",
        "/marco/Hanafuda_March_Kasu_1.svg.png",
        "/marco/Hanafuda_March_Kasu_2.svg.png",
    ],
    [
        "/abril/Hanafuda_April_Kasu_1.svg.png",
        "/abril/Hanafuda_April_Kasu_2.svg.png",
        "/abril/Hanafuda_April_Tane.svg.png",
        "/abril/Hanafuda_April_Tanzaku.svg.png",
    ],
    [
        "/maio/Hanafuda_May_Tane.svg.png",
        "/maio/Hanafuda_May_Tanzaku.svg.png",
        "/maio/Hanafuda_May_Kasu_1.svg.png",
        "/maio/Hanafuda_May_Kasu_2.svg.png",
    ],
    [
        "/junho/Hanafuda_June_Tane.svg.png",
        "/junho/Hanafuda_June_Tanzaku.svg.png",
        "/junho/Hanafuda_June_Kasu_1.svg.png",
        "/junho/Hanafuda_June_Kasu_2.svg.png",
    ],
    [
        "/julho/Hanafuda_July_Tane.svg.png",
        "/julho/Hanafuda_July_Tanzaku.svg.png",
        "/julho/Hanafuda_July_Kasu_1.svg.png",
        "/julho/Hanafuda_July_Kasu_2.svg.png",
    ],
    [
        "/agosto/Hanafuda_August_Tane.svg.png",
        "/agosto/Hanafuda_August_Hikari.svg.png",
        "/agosto/Hanafuda_August_Kasu_1.svg.png",
        "/agosto/Hanafuda_August_Kasu_2.svg.png",
    ],
    [
        "/setembro/Hanafuda_September_Tane.svg.png",
        "/setembro/Hanafuda_September_Tanzaku.svg.png",
        "/setembro/Hanafuda_September_Kasu_1.svg.png",
        "/setembro/Hanafuda_September_Kasu_2.svg.png",
    ],
    [
        "/outubro/Hanafuda_October_Tane.svg.png",
        "/outubro/Hanafuda_October_Tanzaku.svg.png",
        "/outubro/Hanafuda_October_Kasu_1.svg.png",
        "/outubro/Hanafuda_October_Kasu_2.svg.png",
    ],
    [
        "/novembro/Hanafuda_November_Tane.svg.png",
        "/novembro/Hanafuda_November_Hikari.svg.png",
        "/novembro/Hanafuda_November_Tanzaku.svg.png",
        "/novembro/Hanafuda_November_Kasu.svg.png",
    ],
    [
        "/dezembro/Hanafuda_December_Hikari.svg.png",
        "/dezembro/Hanafuda_December_Kasu_1.svg.png",
        "/dezembro/Hanafuda_December_Kasu_2.svg.png",
        "/dezembro/Hanafuda_December_Kasu_3.svg.png",
    ]
]

export default imagens